script: kas: update meta-openembedded layer refspec
This new revision integrate a fix for the following issue:
  Error: Transaction test error:
  file /usr/share/glib-2.0/schemas/org.gnome.nm-applet.gschema.xml
  conflicts between attempted installs of
  network-manager-applet-1.30.0-r0.riscv64 and libnma-1.10.4-r0.riscv64

Signed-off-by: Thomas Perrot <thomas.perrot@bootlin.com>