conf: distro: freedom-u-sdk: use clang as llvm provider
Because there is confict between both:
ERROR: clang-16.0.6-r0 do_package_write_rpm_setscene: The recipe clang
is trying to install files into a shared area when those files already
exist. Those files and their manifest location are:
build/tmp/deploy/rpm/riscv64/liblto16-16.0.6-r0.riscv64.rpm

In addition, that should save compile time and space.

Signed-off-by: Thomas Perrot <thomas.perrot@bootlin.com>