coreutils: no longer provides doc
It is a workaround for the following issue:

ERROR: demo-coreip-cli-1.0-r0 do_rootfs: Postinstall scriptlets
of ['coreutils-doc'] have failed. If the intention is to defer
them to first boot, then please place them into
pkg_postinst_ontarget:${PN} ().

Signed-off-by: Thomas Perrot <thomas.perrot@bootlin.com>